const ApiEndPonits = {
  bsEndPoints: {
    locationDetails: "BHARATSEATS/locationDetails",
    brHeadTypeList: "BHARATSEATS/brHeadTypeList",
    listOfProfile: "BHARATSEATS/listOfProfile",
    menuListForProfile: "BHARATSEATS/menuListForProfile",
    addProfile: "BHARATSEATS/addProfile",
    userTypeList: "BHARATSEATS/userTypeList",
    addUser: "BHARATSEATS/addUser",
    listOfUsers: "BHARATSEATS/listOfUsers",
    updateUser: "BHARATSEATS/updateUser",
    addRole: "BHARATSEATS/addRole",
    listOfMaterial: "BHARATSEATS/listOfMaterial",
    addMaterial: "BHARATSEATS/addMaterial",
    updateMaterial: "BHARATSEATS/updateMaterial",
    searchMaterialFilter: "BHARATSEATS/searchMaterialFilter",
    searchMaterial: "BHARATSEATS/searchMaterial",
    listOfSupplier: "BHARATSEATS/listOfSupplier",
    updateSupplier: "BHARATSEATS/updateSupplier",
    listOfPlant: "BHARATSEATS/listOfPlant",
    updatePlant: "BHARATSEATS/updatePlant",
    listOfUnits: "BHARATSEATS/listOfUnits",
    addPlant: "BHARATSEATS/addPlant",
    addUnit: "BHARATSEATS/addUnit",
    updateUnit: "BHARATSEATS/updateUnit",
    listOfCities: "BHARATSEATS/listOfCities",
    addCity: "BHARATSEATS/addCity",
    updateCity: "BHARATSEATS/updateCity",
    managePO: "BHARATSEATS/managePO",
    manageSchedule: "BHARATSEATS/manageSchedule",
    manageInvoice: "BHARATSEATS/manageInvoice",
    addCompanyProfile: "BHARATSEATS/addCompanyProfile",
    addFinancialDetails: "BHARATSEATS/addFinancialDetails",
    addHRDetails: "BHARATSEATS/addHRDetails",
    addTechnicalDetails: "BHARATSEATS/addTechnicalDetails",
    companyProfiles: "BHARATSEATS/companyProfiles",
    vendorQuestionaire: "BHARATSEATS/vendorQuestionaire",
    listOfFoc: "BHARATSEATS/listOfFoc",
    listOfPPM: "BHARATSEATS/listOfPPM",
    listOfECN: "BHARATSEATS/listOfECN",
  },
};

export default ApiEndPonits;
